// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: traffic/v1/traffic.proto

package trafficV1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTrafficInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RealUpload    int64                  `protobuf:"varint,2,opt,name=realUpload,proto3" json:"realUpload,omitempty"`
	RealDownload  int64                  `protobuf:"varint,3,opt,name=realDownload,proto3" json:"realDownload,omitempty"`
	BonusUpload   int64                  `protobuf:"varint,4,opt,name=bonusUpload,proto3" json:"bonusUpload,omitempty"`
	BonusDownload int64                  `protobuf:"varint,5,opt,name=bonusDownload,proto3" json:"bonusDownload,omitempty"`
	Ratio         float64                `protobuf:"fixed64,6,opt,name=ratio,proto3" json:"ratio,omitempty"`
	UploadRate    int64                  `protobuf:"varint,7,opt,name=uploadRate,proto3" json:"uploadRate,omitempty"`
	DownloadRate  int64                  `protobuf:"varint,8,opt,name=downloadRate,proto3" json:"downloadRate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTrafficInfo) Reset() {
	*x = UserTrafficInfo{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTrafficInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrafficInfo) ProtoMessage() {}

func (x *UserTrafficInfo) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrafficInfo.ProtoReflect.Descriptor instead.
func (*UserTrafficInfo) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *UserTrafficInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTrafficInfo) GetRealUpload() int64 {
	if x != nil {
		return x.RealUpload
	}
	return 0
}

func (x *UserTrafficInfo) GetRealDownload() int64 {
	if x != nil {
		return x.RealDownload
	}
	return 0
}

func (x *UserTrafficInfo) GetBonusUpload() int64 {
	if x != nil {
		return x.BonusUpload
	}
	return 0
}

func (x *UserTrafficInfo) GetBonusDownload() int64 {
	if x != nil {
		return x.BonusDownload
	}
	return 0
}

func (x *UserTrafficInfo) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *UserTrafficInfo) GetUploadRate() int64 {
	if x != nil {
		return x.UploadRate
	}
	return 0
}

func (x *UserTrafficInfo) GetDownloadRate() int64 {
	if x != nil {
		return x.DownloadRate
	}
	return 0
}

type TransferHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TorrentId     string                 `protobuf:"bytes,2,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	TorrentName   string                 `protobuf:"bytes,3,opt,name=torrentName,proto3" json:"torrentName,omitempty"`
	Uploaded      int64                  `protobuf:"varint,4,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	Downloaded    int64                  `protobuf:"varint,5,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	SeedTime      int64                  `protobuf:"varint,6,opt,name=seedTime,proto3" json:"seedTime,omitempty"`
	IsFinished    bool                   `protobuf:"varint,7,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	LastAction    string                 `protobuf:"bytes,9,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHistoryItem) Reset() {
	*x = TransferHistoryItem{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryItem) ProtoMessage() {}

func (x *TransferHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryItem.ProtoReflect.Descriptor instead.
func (*TransferHistoryItem) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *TransferHistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferHistoryItem) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *TransferHistoryItem) GetTorrentName() string {
	if x != nil {
		return x.TorrentName
	}
	return ""
}

func (x *TransferHistoryItem) GetUploaded() int64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *TransferHistoryItem) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *TransferHistoryItem) GetSeedTime() int64 {
	if x != nil {
		return x.SeedTime
	}
	return 0
}

func (x *TransferHistoryItem) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *TransferHistoryItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TransferHistoryItem) GetLastAction() string {
	if x != nil {
		return x.LastAction
	}
	return ""
}

type TorrentStatsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentId     string                 `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	SeedCount     int32                  `protobuf:"varint,2,opt,name=seedCount,proto3" json:"seedCount,omitempty"`
	LeechCount    int32                  `protobuf:"varint,3,opt,name=leechCount,proto3" json:"leechCount,omitempty"`
	SnatchCount   int32                  `protobuf:"varint,4,opt,name=snatchCount,proto3" json:"snatchCount,omitempty"`
	TotalUpload   int64                  `protobuf:"varint,5,opt,name=totalUpload,proto3" json:"totalUpload,omitempty"`
	TotalDownload int64                  `protobuf:"varint,6,opt,name=totalDownload,proto3" json:"totalDownload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentStatsInfo) Reset() {
	*x = TorrentStatsInfo{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentStatsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentStatsInfo) ProtoMessage() {}

func (x *TorrentStatsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentStatsInfo.ProtoReflect.Descriptor instead.
func (*TorrentStatsInfo) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *TorrentStatsInfo) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *TorrentStatsInfo) GetSeedCount() int32 {
	if x != nil {
		return x.SeedCount
	}
	return 0
}

func (x *TorrentStatsInfo) GetLeechCount() int32 {
	if x != nil {
		return x.LeechCount
	}
	return 0
}

func (x *TorrentStatsInfo) GetSnatchCount() int32 {
	if x != nil {
		return x.SnatchCount
	}
	return 0
}

func (x *TorrentStatsInfo) GetTotalUpload() int64 {
	if x != nil {
		return x.TotalUpload
	}
	return 0
}

func (x *TorrentStatsInfo) GetTotalDownload() int64 {
	if x != nil {
		return x.TotalDownload
	}
	return 0
}

type GetUserTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTrafficRequest) Reset() {
	*x = GetUserTrafficRequest{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTrafficRequest) ProtoMessage() {}

func (x *GetUserTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTrafficRequest.ProtoReflect.Descriptor instead.
func (*GetUserTrafficRequest) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserTrafficRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traffic       *UserTrafficInfo       `protobuf:"bytes,1,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTrafficResponse) Reset() {
	*x = GetUserTrafficResponse{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTrafficResponse) ProtoMessage() {}

func (x *GetUserTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTrafficResponse.ProtoReflect.Descriptor instead.
func (*GetUserTrafficResponse) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTrafficResponse) GetTraffic() *UserTrafficInfo {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type ListTransferHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferHistoryRequest) Reset() {
	*x = ListTransferHistoryRequest{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferHistoryRequest) ProtoMessage() {}

func (x *ListTransferHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListTransferHistoryRequest) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransferHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTransferHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransferHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransferHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TransferHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransferHistoryResponse) Reset() {
	*x = ListTransferHistoryResponse{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransferHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransferHistoryResponse) ProtoMessage() {}

func (x *ListTransferHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransferHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListTransferHistoryResponse) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransferHistoryResponse) GetItems() []*TransferHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTransferHistoryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTorrentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentId     string                 `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentStatsRequest) Reset() {
	*x = GetTorrentStatsRequest{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentStatsRequest) ProtoMessage() {}

func (x *GetTorrentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTorrentStatsRequest) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{7}
}

func (x *GetTorrentStatsRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

type GetTorrentStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TorrentStatsInfo      `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentStatsResponse) Reset() {
	*x = GetTorrentStatsResponse{}
	mi := &file_traffic_v1_traffic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentStatsResponse) ProtoMessage() {}

func (x *GetTorrentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_v1_traffic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTorrentStatsResponse) Descriptor() ([]byte, []int) {
	return file_traffic_v1_traffic_proto_rawDescGZIP(), []int{8}
}

func (x *GetTorrentStatsResponse) GetStats() *TorrentStatsInfo {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_traffic_v1_traffic_proto protoreflect.FileDescriptor

const file_traffic_v1_traffic_proto_rawDesc = "" +
	"\n" +
	"\x18traffic/v1/traffic.proto\x12\n" +
	"traffic.v1\x1a\x1cgoogle/api/annotations.proto\"\x8f\x02\n" +
	"\x0fUserTrafficInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"realUpload\x18\x02 \x01(\x03R\n" +
	"realUpload\x12\"\n" +
	"\frealDownload\x18\x03 \x01(\x03R\frealDownload\x12 \n" +
	"\vbonusUpload\x18\x04 \x01(\x03R\vbonusUpload\x12$\n" +
	"\rbonusDownload\x18\x05 \x01(\x03R\rbonusDownload\x12\x14\n" +
	"\x05ratio\x18\x06 \x01(\x01R\x05ratio\x12\x1e\n" +
	"\n" +
	"uploadRate\x18\a \x01(\x03R\n" +
	"uploadRate\x12\"\n" +
	"\fdownloadRate\x18\b \x01(\x03R\fdownloadRate\"\x99\x02\n" +
	"\x13TransferHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttorrentId\x18\x02 \x01(\tR\ttorrentId\x12 \n" +
	"\vtorrentName\x18\x03 \x01(\tR\vtorrentName\x12\x1a\n" +
	"\buploaded\x18\x04 \x01(\x03R\buploaded\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x05 \x01(\x03R\n" +
	"downloaded\x12\x1a\n" +
	"\bseedTime\x18\x06 \x01(\x03R\bseedTime\x12\x1e\n" +
	"\n" +
	"isFinished\x18\a \x01(\bR\n" +
	"isFinished\x12\x1a\n" +
	"\bisActive\x18\b \x01(\bR\bisActive\x12\x1e\n" +
	"\n" +
	"lastAction\x18\t \x01(\tR\n" +
	"lastAction\"\xd8\x01\n" +
	"\x10TorrentStatsInfo\x12\x1c\n" +
	"\ttorrentId\x18\x01 \x01(\tR\ttorrentId\x12\x1c\n" +
	"\tseedCount\x18\x02 \x01(\x05R\tseedCount\x12\x1e\n" +
	"\n" +
	"leechCount\x18\x03 \x01(\x05R\n" +
	"leechCount\x12 \n" +
	"\vsnatchCount\x18\x04 \x01(\x05R\vsnatchCount\x12 \n" +
	"\vtotalUpload\x18\x05 \x01(\x03R\vtotalUpload\x12$\n" +
	"\rtotalDownload\x18\x06 \x01(\x03R\rtotalDownload\"/\n" +
	"\x15GetUserTrafficRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x16GetUserTrafficResponse\x125\n" +
	"\atraffic\x18\x01 \x01(\v2\x1b.traffic.v1.UserTrafficInfoR\atraffic\"d\n" +
	"\x1aListTransferHistoryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"j\n" +
	"\x1bListTransferHistoryResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.traffic.v1.TransferHistoryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"6\n" +
	"\x16GetTorrentStatsRequest\x12\x1c\n" +
	"\ttorrentId\x18\x01 \x01(\tR\ttorrentId\"M\n" +
	"\x17GetTorrentStatsResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1c.traffic.v1.TorrentStatsInfoR\x05stats2\x9a\x03\n" +
	"\x0eTrafficService\x12y\n" +
	"\x0eGetUserTraffic\x12!.traffic.v1.GetUserTrafficRequest\x1a\".traffic.v1.GetUserTrafficResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/gapi/traffic/v1/user\x12\x8b\x01\n" +
	"\x13ListTransferHistory\x12&.traffic.v1.ListTransferHistoryRequest\x1a'.traffic.v1.ListTransferHistoryResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/gapi/traffic/v1/history\x12\x7f\n" +
	"\x0fGetTorrentStats\x12\".traffic.v1.GetTorrentStatsRequest\x1a#.traffic.v1.GetTorrentStatsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/gapi/traffic/v1/torrentBAZ?github.com/GoldenSheep402/Hermes/pkg/proto/traffic/v1;trafficV1b\x06proto3"

var (
	file_traffic_v1_traffic_proto_rawDescOnce sync.Once
	file_traffic_v1_traffic_proto_rawDescData []byte
)

func file_traffic_v1_traffic_proto_rawDescGZIP() []byte {
	file_traffic_v1_traffic_proto_rawDescOnce.Do(func() {
		file_traffic_v1_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traffic_v1_traffic_proto_rawDesc), len(file_traffic_v1_traffic_proto_rawDesc)))
	})
	return file_traffic_v1_traffic_proto_rawDescData
}

var file_traffic_v1_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_traffic_v1_traffic_proto_goTypes = []any{
	(*UserTrafficInfo)(nil),             // 0: traffic.v1.UserTrafficInfo
	(*TransferHistoryItem)(nil),         // 1: traffic.v1.TransferHistoryItem
	(*TorrentStatsInfo)(nil),            // 2: traffic.v1.TorrentStatsInfo
	(*GetUserTrafficRequest)(nil),       // 3: traffic.v1.GetUserTrafficRequest
	(*GetUserTrafficResponse)(nil),      // 4: traffic.v1.GetUserTrafficResponse
	(*ListTransferHistoryRequest)(nil),  // 5: traffic.v1.ListTransferHistoryRequest
	(*ListTransferHistoryResponse)(nil), // 6: traffic.v1.ListTransferHistoryResponse
	(*GetTorrentStatsRequest)(nil),      // 7: traffic.v1.GetTorrentStatsRequest
	(*GetTorrentStatsResponse)(nil),     // 8: traffic.v1.GetTorrentStatsResponse
}
var file_traffic_v1_traffic_proto_depIdxs = []int32{
	0, // 0: traffic.v1.GetUserTrafficResponse.traffic:type_name -> traffic.v1.UserTrafficInfo
	1, // 1: traffic.v1.ListTransferHistoryResponse.items:type_name -> traffic.v1.TransferHistoryItem
	2, // 2: traffic.v1.GetTorrentStatsResponse.stats:type_name -> traffic.v1.TorrentStatsInfo
	3, // 3: traffic.v1.TrafficService.GetUserTraffic:input_type -> traffic.v1.GetUserTrafficRequest
	5, // 4: traffic.v1.TrafficService.ListTransferHistory:input_type -> traffic.v1.ListTransferHistoryRequest
	7, // 5: traffic.v1.TrafficService.GetTorrentStats:input_type -> traffic.v1.GetTorrentStatsRequest
	4, // 6: traffic.v1.TrafficService.GetUserTraffic:output_type -> traffic.v1.GetUserTrafficResponse
	6, // 7: traffic.v1.TrafficService.ListTransferHistory:output_type -> traffic.v1.ListTransferHistoryResponse
	8, // 8: traffic.v1.TrafficService.GetTorrentStats:output_type -> traffic.v1.GetTorrentStatsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_traffic_v1_traffic_proto_init() }
func file_traffic_v1_traffic_proto_init() {
	if File_traffic_v1_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traffic_v1_traffic_proto_rawDesc), len(file_traffic_v1_traffic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_traffic_v1_traffic_proto_goTypes,
		DependencyIndexes: file_traffic_v1_traffic_proto_depIdxs,
		MessageInfos:      file_traffic_v1_traffic_proto_msgTypes,
	}.Build()
	File_traffic_v1_traffic_proto = out.File
	file_traffic_v1_traffic_proto_goTypes = nil
	file_traffic_v1_traffic_proto_depIdxs = nil
}
