Mode: debug
Port: "27811"
Log:
    LogPath: "./latest.log"
    CLS:
        Endpoint: ""
        AccessKey: ""
        AccessToken: ""
        TopicID: ""
B2:
    BucketKeyID: ""
    BucketKey: ""
    BucketName: ""
Pyroscope:
    ApplicationName: ""
    ServerAddress: ""
    BasicAuthUser: ""
    BasicAuthPass: ""
    TenantID: ""
Uptrace:
    ServiceName: ""
    ServiceVersion: ""
    DSN: ""
SentryDsn: ""
Pgsql:
    Addr: "hermes-postgres"
    Port: "5432"
    User: "hermes"
    Password: "123456"
    Database: "hermes"
Rds:
    Addr: "hermes-rds"
    Port: "16379"
    Password: ""
    DB: 0
uptrace:
    DSN: ""
    ServiceName: ""
    ServiceVersion: ""
user:
    AdminName: "admin"
    AdminAccount: "admin@admin.com"
    AdminPassword: "admin@admin.com"
TrackerV1:
    Endpoint: "http://172.16.7.183:27811/tracker/announce/key/"
    AllowedSubnets: [
    ]