version: '3.8'

services:
  template-main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hermes
    volumes:
      - /root/Hermes/config.yaml:/Serve/config/config.yaml
      - /root/Hermes/Caddyfile:/etc/caddy/Caddyfile
    network_mode: host
    ports:
      - "80:80"
