version: '3'

services:
  hermes-rds:
    image: redis
    container_name: hermes-rds-ctn
    ports:
      - "6379:6379"
  hermes-postgres:
    image: bitnami/postgresql:latest
    container_name: hermes-ctn
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=hermes
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=hermes