version: '3.8'

services:
  hermes-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/Serve/config.yaml
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /root/Hermes/supervisord.conf:/Serve/supervisord.conf
      - ./log-docker.log:/Serve/latest.log
    container_name: hermes
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - hermes-rds
      - hermes-postgres
    network_mode: host

  hermes-rds:
    image: redis
    container_name: hermes-rds-ctn-template
    ports:
      - "26379:6379"
    networks:
      - hermes-network
    volumes:
      - /root/dev/Hermes/rds-data:/data

  hermes-postgres:
    image: postgres:latest
    container_name: hermes-ctn-template
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=hermes
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hermes
    networks:
      - hermes-network
    volumes:
      - /root/dev/Hermes/pg-data:/var/lib/postgresql/data

networks:
  hermes-network:
    driver: bridge
