version: '3'

services:
  jframe-rds:
    image: redis
    container_name: jframe-rds-ctn
    ports:
      - "6379:6379"
  jframe-mysql:
    image: bitnami/mysql:latest
    container_name: jframe-mysql-ctn
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jframe
      - MYSQL_CHARSET=utf8mb4
