// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: torrent/v1/torrent.proto

package torrentV1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TorrentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InfoHash      string                 `protobuf:"bytes,2,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	UploaderId    string                 `protobuf:"bytes,3,opt,name=uploaderId,proto3" json:"uploaderId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	IsSingleFile  bool                   `protobuf:"varint,6,opt,name=isSingleFile,proto3" json:"isSingleFile,omitempty"`
	FileCount     int32                  `protobuf:"varint,7,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
	SeedCount     int32                  `protobuf:"varint,8,opt,name=seedCount,proto3" json:"seedCount,omitempty"`
	LeechCount    int32                  `protobuf:"varint,9,opt,name=leechCount,proto3" json:"leechCount,omitempty"`
	SnatchCount   int32                  `protobuf:"varint,10,opt,name=snatchCount,proto3" json:"snatchCount,omitempty"`
	IsActive      bool                   `protobuf:"varint,11,opt,name=isActive,proto3" json:"isActive,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentInfo) Reset() {
	*x = TorrentInfo{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentInfo) ProtoMessage() {}

func (x *TorrentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentInfo.ProtoReflect.Descriptor instead.
func (*TorrentInfo) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{0}
}

func (x *TorrentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentInfo) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *TorrentInfo) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *TorrentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TorrentInfo) GetIsSingleFile() bool {
	if x != nil {
		return x.IsSingleFile
	}
	return false
}

func (x *TorrentInfo) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *TorrentInfo) GetSeedCount() int32 {
	if x != nil {
		return x.SeedCount
	}
	return 0
}

func (x *TorrentInfo) GetLeechCount() int32 {
	if x != nil {
		return x.LeechCount
	}
	return 0
}

func (x *TorrentInfo) GetSnatchCount() int32 {
	if x != nil {
		return x.SnatchCount
	}
	return 0
}

func (x *TorrentInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TorrentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TorrentFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TorrentId     string                 `protobuf:"bytes,2,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentFile) Reset() {
	*x = TorrentFile{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentFile) ProtoMessage() {}

func (x *TorrentFile) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentFile.ProtoReflect.Descriptor instead.
func (*TorrentFile) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{1}
}

func (x *TorrentFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentFile) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *TorrentFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TorrentFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentData   []byte                 `protobuf:"bytes,1,opt,name=torrentData,proto3" json:"torrentData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTorrentRequest) Reset() {
	*x = UploadTorrentRequest{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTorrentRequest) ProtoMessage() {}

func (x *UploadTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTorrentRequest.ProtoReflect.Descriptor instead.
func (*UploadTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{2}
}

func (x *UploadTorrentRequest) GetTorrentData() []byte {
	if x != nil {
		return x.TorrentData
	}
	return nil
}

type UploadTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentId     string                 `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	InfoHash      string                 `protobuf:"bytes,2,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTorrentResponse) Reset() {
	*x = UploadTorrentResponse{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTorrentResponse) ProtoMessage() {}

func (x *UploadTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTorrentResponse.ProtoReflect.Descriptor instead.
func (*UploadTorrentResponse) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{3}
}

func (x *UploadTorrentResponse) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *UploadTorrentResponse) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type DownloadTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentId     string                 `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTorrentRequest) Reset() {
	*x = DownloadTorrentRequest{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTorrentRequest) ProtoMessage() {}

func (x *DownloadTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTorrentRequest.ProtoReflect.Descriptor instead.
func (*DownloadTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadTorrentRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

type DownloadTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentData   []byte                 `protobuf:"bytes,1,opt,name=torrentData,proto3" json:"torrentData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTorrentResponse) Reset() {
	*x = DownloadTorrentResponse{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTorrentResponse) ProtoMessage() {}

func (x *DownloadTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTorrentResponse.ProtoReflect.Descriptor instead.
func (*DownloadTorrentResponse) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadTorrentResponse) GetTorrentData() []byte {
	if x != nil {
		return x.TorrentData
	}
	return nil
}

type GetTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentRequest) Reset() {
	*x = GetTorrentRequest{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentRequest) ProtoMessage() {}

func (x *GetTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentRequest.ProtoReflect.Descriptor instead.
func (*GetTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{6}
}

func (x *GetTorrentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrent       *TorrentInfo           `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentResponse) Reset() {
	*x = GetTorrentResponse{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentResponse) ProtoMessage() {}

func (x *GetTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentResponse.ProtoReflect.Descriptor instead.
func (*GetTorrentResponse) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{7}
}

func (x *GetTorrentResponse) GetTorrent() *TorrentInfo {
	if x != nil {
		return x.Torrent
	}
	return nil
}

type ListTorrentFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentId     string                 `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentFilesRequest) Reset() {
	*x = ListTorrentFilesRequest{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentFilesRequest) ProtoMessage() {}

func (x *ListTorrentFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentFilesRequest.ProtoReflect.Descriptor instead.
func (*ListTorrentFilesRequest) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{8}
}

func (x *ListTorrentFilesRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

type ListTorrentFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*TorrentFile         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentFilesResponse) Reset() {
	*x = ListTorrentFilesResponse{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentFilesResponse) ProtoMessage() {}

func (x *ListTorrentFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentFilesResponse.ProtoReflect.Descriptor instead.
func (*ListTorrentFilesResponse) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{9}
}

func (x *ListTorrentFilesResponse) GetFiles() []*TorrentFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type DeleteTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTorrentRequest) Reset() {
	*x = DeleteTorrentRequest{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTorrentRequest) ProtoMessage() {}

func (x *DeleteTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTorrentRequest.ProtoReflect.Descriptor instead.
func (*DeleteTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTorrentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTorrentResponse) Reset() {
	*x = DeleteTorrentResponse{}
	mi := &file_torrent_v1_torrent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTorrentResponse) ProtoMessage() {}

func (x *DeleteTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_v1_torrent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTorrentResponse.ProtoReflect.Descriptor instead.
func (*DeleteTorrentResponse) Descriptor() ([]byte, []int) {
	return file_torrent_v1_torrent_proto_rawDescGZIP(), []int{11}
}

var File_torrent_v1_torrent_proto protoreflect.FileDescriptor

const file_torrent_v1_torrent_proto_rawDesc = "" +
	"\n" +
	"\x18torrent/v1/torrent.proto\x12\n" +
	"torrent.v1\x1a\x1cgoogle/api/annotations.proto\"\xdd\x02\n" +
	"\vTorrentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\binfoHash\x18\x02 \x01(\tR\binfoHash\x12\x1e\n" +
	"\n" +
	"uploaderId\x18\x03 \x01(\tR\n" +
	"uploaderId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\"\n" +
	"\fisSingleFile\x18\x06 \x01(\bR\fisSingleFile\x12\x1c\n" +
	"\tfileCount\x18\a \x01(\x05R\tfileCount\x12\x1c\n" +
	"\tseedCount\x18\b \x01(\x05R\tseedCount\x12\x1e\n" +
	"\n" +
	"leechCount\x18\t \x01(\x05R\n" +
	"leechCount\x12 \n" +
	"\vsnatchCount\x18\n" +
	" \x01(\x05R\vsnatchCount\x12\x1a\n" +
	"\bisActive\x18\v \x01(\bR\bisActive\x12\x1c\n" +
	"\tcreatedAt\x18\f \x01(\tR\tcreatedAt\"c\n" +
	"\vTorrentFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttorrentId\x18\x02 \x01(\tR\ttorrentId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"8\n" +
	"\x14UploadTorrentRequest\x12 \n" +
	"\vtorrentData\x18\x01 \x01(\fR\vtorrentData\"Q\n" +
	"\x15UploadTorrentResponse\x12\x1c\n" +
	"\ttorrentId\x18\x01 \x01(\tR\ttorrentId\x12\x1a\n" +
	"\binfoHash\x18\x02 \x01(\tR\binfoHash\"6\n" +
	"\x16DownloadTorrentRequest\x12\x1c\n" +
	"\ttorrentId\x18\x01 \x01(\tR\ttorrentId\";\n" +
	"\x17DownloadTorrentResponse\x12 \n" +
	"\vtorrentData\x18\x01 \x01(\fR\vtorrentData\"#\n" +
	"\x11GetTorrentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x12GetTorrentResponse\x121\n" +
	"\atorrent\x18\x01 \x01(\v2\x17.torrent.v1.TorrentInfoR\atorrent\"7\n" +
	"\x17ListTorrentFilesRequest\x12\x1c\n" +
	"\ttorrentId\x18\x01 \x01(\tR\ttorrentId\"I\n" +
	"\x18ListTorrentFilesResponse\x12-\n" +
	"\x05files\x18\x01 \x03(\v2\x17.torrent.v1.TorrentFileR\x05files\"&\n" +
	"\x14DeleteTorrentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteTorrentResponse2\xf9\x04\n" +
	"\x0eTorrentService\x12x\n" +
	"\rUploadTorrent\x12 .torrent.v1.UploadTorrentRequest\x1a!.torrent.v1.UploadTorrentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/gapi/torrent/v1/upload\x12\x80\x01\n" +
	"\x0fDownloadTorrent\x12\".torrent.v1.DownloadTorrentRequest\x1a#.torrent.v1.DownloadTorrentResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/gapi/torrent/v1/download\x12m\n" +
	"\n" +
	"GetTorrent\x12\x1d.torrent.v1.GetTorrentRequest\x1a\x1e.torrent.v1.GetTorrentResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/gapi/torrent/v1/info\x12\x80\x01\n" +
	"\x10ListTorrentFiles\x12#.torrent.v1.ListTorrentFilesRequest\x1a$.torrent.v1.ListTorrentFilesResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/gapi/torrent/v1/files\x12x\n" +
	"\rDeleteTorrent\x12 .torrent.v1.DeleteTorrentRequest\x1a!.torrent.v1.DeleteTorrentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/gapi/torrent/v1/deleteBAZ?github.com/GoldenSheep402/Hermes/pkg/proto/torrent/v1;torrentV1b\x06proto3"

var (
	file_torrent_v1_torrent_proto_rawDescOnce sync.Once
	file_torrent_v1_torrent_proto_rawDescData []byte
)

func file_torrent_v1_torrent_proto_rawDescGZIP() []byte {
	file_torrent_v1_torrent_proto_rawDescOnce.Do(func() {
		file_torrent_v1_torrent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_torrent_v1_torrent_proto_rawDesc), len(file_torrent_v1_torrent_proto_rawDesc)))
	})
	return file_torrent_v1_torrent_proto_rawDescData
}

var file_torrent_v1_torrent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_torrent_v1_torrent_proto_goTypes = []any{
	(*TorrentInfo)(nil),              // 0: torrent.v1.TorrentInfo
	(*TorrentFile)(nil),              // 1: torrent.v1.TorrentFile
	(*UploadTorrentRequest)(nil),     // 2: torrent.v1.UploadTorrentRequest
	(*UploadTorrentResponse)(nil),    // 3: torrent.v1.UploadTorrentResponse
	(*DownloadTorrentRequest)(nil),   // 4: torrent.v1.DownloadTorrentRequest
	(*DownloadTorrentResponse)(nil),  // 5: torrent.v1.DownloadTorrentResponse
	(*GetTorrentRequest)(nil),        // 6: torrent.v1.GetTorrentRequest
	(*GetTorrentResponse)(nil),       // 7: torrent.v1.GetTorrentResponse
	(*ListTorrentFilesRequest)(nil),  // 8: torrent.v1.ListTorrentFilesRequest
	(*ListTorrentFilesResponse)(nil), // 9: torrent.v1.ListTorrentFilesResponse
	(*DeleteTorrentRequest)(nil),     // 10: torrent.v1.DeleteTorrentRequest
	(*DeleteTorrentResponse)(nil),    // 11: torrent.v1.DeleteTorrentResponse
}
var file_torrent_v1_torrent_proto_depIdxs = []int32{
	0,  // 0: torrent.v1.GetTorrentResponse.torrent:type_name -> torrent.v1.TorrentInfo
	1,  // 1: torrent.v1.ListTorrentFilesResponse.files:type_name -> torrent.v1.TorrentFile
	2,  // 2: torrent.v1.TorrentService.UploadTorrent:input_type -> torrent.v1.UploadTorrentRequest
	4,  // 3: torrent.v1.TorrentService.DownloadTorrent:input_type -> torrent.v1.DownloadTorrentRequest
	6,  // 4: torrent.v1.TorrentService.GetTorrent:input_type -> torrent.v1.GetTorrentRequest
	8,  // 5: torrent.v1.TorrentService.ListTorrentFiles:input_type -> torrent.v1.ListTorrentFilesRequest
	10, // 6: torrent.v1.TorrentService.DeleteTorrent:input_type -> torrent.v1.DeleteTorrentRequest
	3,  // 7: torrent.v1.TorrentService.UploadTorrent:output_type -> torrent.v1.UploadTorrentResponse
	5,  // 8: torrent.v1.TorrentService.DownloadTorrent:output_type -> torrent.v1.DownloadTorrentResponse
	7,  // 9: torrent.v1.TorrentService.GetTorrent:output_type -> torrent.v1.GetTorrentResponse
	9,  // 10: torrent.v1.TorrentService.ListTorrentFiles:output_type -> torrent.v1.ListTorrentFilesResponse
	11, // 11: torrent.v1.TorrentService.DeleteTorrent:output_type -> torrent.v1.DeleteTorrentResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_torrent_v1_torrent_proto_init() }
func file_torrent_v1_torrent_proto_init() {
	if File_torrent_v1_torrent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_torrent_v1_torrent_proto_rawDesc), len(file_torrent_v1_torrent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_torrent_v1_torrent_proto_goTypes,
		DependencyIndexes: file_torrent_v1_torrent_proto_depIdxs,
		MessageInfos:      file_torrent_v1_torrent_proto_msgTypes,
	}.Build()
	File_torrent_v1_torrent_proto = out.File
	file_torrent_v1_torrent_proto_goTypes = nil
	file_torrent_v1_torrent_proto_depIdxs = nil
}
