// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: invite/v1/invite.proto

package inviteV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InviteService_CreateInviteCode_FullMethodName  = "/invite.v1.InviteService/CreateInviteCode"
	InviteService_ListInviteCodes_FullMethodName   = "/invite.v1.InviteService/ListInviteCodes"
	InviteService_ConsumeInviteCode_FullMethodName = "/invite.v1.InviteService/ConsumeInviteCode"
)

// InviteServiceClient is the client API for InviteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InviteServiceClient interface {
	CreateInviteCode(ctx context.Context, in *CreateInviteCodeRequest, opts ...grpc.CallOption) (*CreateInviteCodeResponse, error)
	ListInviteCodes(ctx context.Context, in *ListInviteCodesRequest, opts ...grpc.CallOption) (*ListInviteCodesResponse, error)
	ConsumeInviteCode(ctx context.Context, in *ConsumeInviteCodeRequest, opts ...grpc.CallOption) (*ConsumeInviteCodeResponse, error)
}

type inviteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInviteServiceClient(cc grpc.ClientConnInterface) InviteServiceClient {
	return &inviteServiceClient{cc}
}

func (c *inviteServiceClient) CreateInviteCode(ctx context.Context, in *CreateInviteCodeRequest, opts ...grpc.CallOption) (*CreateInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInviteCodeResponse)
	err := c.cc.Invoke(ctx, InviteService_CreateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) ListInviteCodes(ctx context.Context, in *ListInviteCodesRequest, opts ...grpc.CallOption) (*ListInviteCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInviteCodesResponse)
	err := c.cc.Invoke(ctx, InviteService_ListInviteCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteServiceClient) ConsumeInviteCode(ctx context.Context, in *ConsumeInviteCodeRequest, opts ...grpc.CallOption) (*ConsumeInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeInviteCodeResponse)
	err := c.cc.Invoke(ctx, InviteService_ConsumeInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InviteServiceServer is the server API for InviteService service.
// All implementations must embed UnimplementedInviteServiceServer
// for forward compatibility.
type InviteServiceServer interface {
	CreateInviteCode(context.Context, *CreateInviteCodeRequest) (*CreateInviteCodeResponse, error)
	ListInviteCodes(context.Context, *ListInviteCodesRequest) (*ListInviteCodesResponse, error)
	ConsumeInviteCode(context.Context, *ConsumeInviteCodeRequest) (*ConsumeInviteCodeResponse, error)
	mustEmbedUnimplementedInviteServiceServer()
}

// UnimplementedInviteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInviteServiceServer struct{}

func (UnimplementedInviteServiceServer) CreateInviteCode(context.Context, *CreateInviteCodeRequest) (*CreateInviteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInviteCode not implemented")
}
func (UnimplementedInviteServiceServer) ListInviteCodes(context.Context, *ListInviteCodesRequest) (*ListInviteCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInviteCodes not implemented")
}
func (UnimplementedInviteServiceServer) ConsumeInviteCode(context.Context, *ConsumeInviteCodeRequest) (*ConsumeInviteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeInviteCode not implemented")
}
func (UnimplementedInviteServiceServer) mustEmbedUnimplementedInviteServiceServer() {}
func (UnimplementedInviteServiceServer) testEmbeddedByValue()                       {}

// UnsafeInviteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InviteServiceServer will
// result in compilation errors.
type UnsafeInviteServiceServer interface {
	mustEmbedUnimplementedInviteServiceServer()
}

func RegisterInviteServiceServer(s grpc.ServiceRegistrar, srv InviteServiceServer) {
	// If the following call panics, it indicates UnimplementedInviteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InviteService_ServiceDesc, srv)
}

func _InviteService_CreateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).CreateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_CreateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).CreateInviteCode(ctx, req.(*CreateInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_ListInviteCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInviteCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).ListInviteCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_ListInviteCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).ListInviteCodes(ctx, req.(*ListInviteCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InviteService_ConsumeInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteServiceServer).ConsumeInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InviteService_ConsumeInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteServiceServer).ConsumeInviteCode(ctx, req.(*ConsumeInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InviteService_ServiceDesc is the grpc.ServiceDesc for InviteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InviteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invite.v1.InviteService",
	HandlerType: (*InviteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInviteCode",
			Handler:    _InviteService_CreateInviteCode_Handler,
		},
		{
			MethodName: "ListInviteCodes",
			Handler:    _InviteService_ListInviteCodes_Handler,
		},
		{
			MethodName: "ConsumeInviteCode",
			Handler:    _InviteService_ConsumeInviteCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invite/v1/invite.proto",
}
