// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invite/v1/invite.proto

package inviteV1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteCodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=senderName,proto3" json:"senderName,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,5,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,6,opt,name=receiverName,proto3" json:"receiverName,omitempty"`
	IsUsed        bool                   `protobuf:"varint,7,opt,name=isUsed,proto3" json:"isUsed,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,8,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	UsedAt        string                 `protobuf:"bytes,9,opt,name=usedAt,proto3" json:"usedAt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCodeInfo) Reset() {
	*x = InviteCodeInfo{}
	mi := &file_invite_v1_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCodeInfo) ProtoMessage() {}

func (x *InviteCodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCodeInfo.ProtoReflect.Descriptor instead.
func (*InviteCodeInfo) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{0}
}

func (x *InviteCodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InviteCodeInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InviteCodeInfo) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *InviteCodeInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InviteCodeInfo) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *InviteCodeInfo) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *InviteCodeInfo) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

func (x *InviteCodeInfo) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *InviteCodeInfo) GetUsedAt() string {
	if x != nil {
		return x.UsedAt
	}
	return ""
}

func (x *InviteCodeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteCodeRequest) Reset() {
	*x = CreateInviteCodeRequest{}
	mi := &file_invite_v1_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteCodeRequest) ProtoMessage() {}

func (x *CreateInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInviteCodeRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteCodeResponse) Reset() {
	*x = CreateInviteCodeResponse{}
	mi := &file_invite_v1_invite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteCodeResponse) ProtoMessage() {}

func (x *CreateInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInviteCodeResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type ListInviteCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInviteCodesRequest) Reset() {
	*x = ListInviteCodesRequest{}
	mi := &file_invite_v1_invite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInviteCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteCodesRequest) ProtoMessage() {}

func (x *ListInviteCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteCodesRequest.ProtoReflect.Descriptor instead.
func (*ListInviteCodesRequest) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{3}
}

func (x *ListInviteCodesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInviteCodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListInviteCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []*InviteCodeInfo      `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInviteCodesResponse) Reset() {
	*x = ListInviteCodesResponse{}
	mi := &file_invite_v1_invite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInviteCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteCodesResponse) ProtoMessage() {}

func (x *ListInviteCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteCodesResponse.ProtoReflect.Descriptor instead.
func (*ListInviteCodesResponse) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{4}
}

func (x *ListInviteCodesResponse) GetCodes() []*InviteCodeInfo {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *ListInviteCodesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConsumeInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeInviteCodeRequest) Reset() {
	*x = ConsumeInviteCodeRequest{}
	mi := &file_invite_v1_invite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeInviteCodeRequest) ProtoMessage() {}

func (x *ConsumeInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeInviteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConsumeInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeInviteCodeResponse) Reset() {
	*x = ConsumeInviteCodeResponse{}
	mi := &file_invite_v1_invite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeInviteCodeResponse) ProtoMessage() {}

func (x *ConsumeInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_v1_invite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_invite_v1_invite_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeInviteCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_invite_v1_invite_proto protoreflect.FileDescriptor

const file_invite_v1_invite_proto_rawDesc = "" +
	"\n" +
	"\x16invite/v1/invite.proto\x12\tinvite.v1\x1a\x1cgoogle/api/annotations.proto\"\xa0\x02\n" +
	"\x0eInviteCodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"senderName\x18\x04 \x01(\tR\n" +
	"senderName\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x05 \x01(\tR\n" +
	"receiverId\x12\"\n" +
	"\freceiverName\x18\x06 \x01(\tR\freceiverName\x12\x16\n" +
	"\x06isUsed\x18\a \x01(\bR\x06isUsed\x12\x1c\n" +
	"\texpiredAt\x18\b \x01(\tR\texpiredAt\x12\x16\n" +
	"\x06usedAt\x18\t \x01(\tR\x06usedAt\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\"/\n" +
	"\x17CreateInviteCodeRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"0\n" +
	"\x18CreateInviteCodeResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"H\n" +
	"\x16ListInviteCodesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"`\n" +
	"\x17ListInviteCodesResponse\x12/\n" +
	"\x05codes\x18\x01 \x03(\v2\x19.invite.v1.InviteCodeInfoR\x05codes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\".\n" +
	"\x18ConsumeInviteCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"5\n" +
	"\x19ConsumeInviteCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x03\n" +
	"\rInviteService\x12~\n" +
	"\x10CreateInviteCode\x12\".invite.v1.CreateInviteCodeRequest\x1a#.invite.v1.CreateInviteCodeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/gapi/invite/v1/create\x12y\n" +
	"\x0fListInviteCodes\x12!.invite.v1.ListInviteCodesRequest\x1a\".invite.v1.ListInviteCodesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/gapi/invite/v1/list\x12\x82\x01\n" +
	"\x11ConsumeInviteCode\x12#.invite.v1.ConsumeInviteCodeRequest\x1a$.invite.v1.ConsumeInviteCodeResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/gapi/invite/v1/consumeB?Z=github.com/GoldenSheep402/Hermes/pkg/proto/invite/v1;inviteV1b\x06proto3"

var (
	file_invite_v1_invite_proto_rawDescOnce sync.Once
	file_invite_v1_invite_proto_rawDescData []byte
)

func file_invite_v1_invite_proto_rawDescGZIP() []byte {
	file_invite_v1_invite_proto_rawDescOnce.Do(func() {
		file_invite_v1_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invite_v1_invite_proto_rawDesc), len(file_invite_v1_invite_proto_rawDesc)))
	})
	return file_invite_v1_invite_proto_rawDescData
}

var file_invite_v1_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_invite_v1_invite_proto_goTypes = []any{
	(*InviteCodeInfo)(nil),            // 0: invite.v1.InviteCodeInfo
	(*CreateInviteCodeRequest)(nil),   // 1: invite.v1.CreateInviteCodeRequest
	(*CreateInviteCodeResponse)(nil),  // 2: invite.v1.CreateInviteCodeResponse
	(*ListInviteCodesRequest)(nil),    // 3: invite.v1.ListInviteCodesRequest
	(*ListInviteCodesResponse)(nil),   // 4: invite.v1.ListInviteCodesResponse
	(*ConsumeInviteCodeRequest)(nil),  // 5: invite.v1.ConsumeInviteCodeRequest
	(*ConsumeInviteCodeResponse)(nil), // 6: invite.v1.ConsumeInviteCodeResponse
}
var file_invite_v1_invite_proto_depIdxs = []int32{
	0, // 0: invite.v1.ListInviteCodesResponse.codes:type_name -> invite.v1.InviteCodeInfo
	1, // 1: invite.v1.InviteService.CreateInviteCode:input_type -> invite.v1.CreateInviteCodeRequest
	3, // 2: invite.v1.InviteService.ListInviteCodes:input_type -> invite.v1.ListInviteCodesRequest
	5, // 3: invite.v1.InviteService.ConsumeInviteCode:input_type -> invite.v1.ConsumeInviteCodeRequest
	2, // 4: invite.v1.InviteService.CreateInviteCode:output_type -> invite.v1.CreateInviteCodeResponse
	4, // 5: invite.v1.InviteService.ListInviteCodes:output_type -> invite.v1.ListInviteCodesResponse
	6, // 6: invite.v1.InviteService.ConsumeInviteCode:output_type -> invite.v1.ConsumeInviteCodeResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_invite_v1_invite_proto_init() }
func file_invite_v1_invite_proto_init() {
	if File_invite_v1_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invite_v1_invite_proto_rawDesc), len(file_invite_v1_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invite_v1_invite_proto_goTypes,
		DependencyIndexes: file_invite_v1_invite_proto_depIdxs,
		MessageInfos:      file_invite_v1_invite_proto_msgTypes,
	}.Build()
	File_invite_v1_invite_proto = out.File
	file_invite_v1_invite_proto_goTypes = nil
	file_invite_v1_invite_proto_depIdxs = nil
}
