// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/system.proto

package systemV1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Setting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Setting) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Setting) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*Setting             `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettingsResponse) GetSettings() []*Setting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *GetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *Setting               `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingResponse) Reset() {
	*x = GetSettingResponse{}
	mi := &file_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingResponse) ProtoMessage() {}

func (x *GetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSettingResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *GetSettingResponse) GetSetting() *Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type SetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*Setting             `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsRequest) Reset() {
	*x = SetSettingsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsRequest) ProtoMessage() {}

func (x *SetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *SetSettingsRequest) GetSettings() []*Setting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsResponse) Reset() {
	*x = SetSettingsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsResponse) ProtoMessage() {}

func (x *SetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{6}
}

type DeleteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSettingRequest) Reset() {
	*x = DeleteSettingRequest{}
	mi := &file_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSettingRequest) ProtoMessage() {}

func (x *DeleteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteSettingRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSettingResponse) Reset() {
	*x = DeleteSettingResponse{}
	mi := &file_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSettingResponse) ProtoMessage() {}

func (x *DeleteSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSettingResponse.ProtoReflect.Descriptor instead.
func (*DeleteSettingResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{8}
}

type GetSiteStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteStatsRequest) Reset() {
	*x = GetSiteStatsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteStatsRequest) ProtoMessage() {}

func (x *GetSiteStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSiteStatsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{9}
}

type GetSiteStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers     int64                  `protobuf:"varint,1,opt,name=totalUsers,proto3" json:"totalUsers,omitempty"`
	TotalTorrents  int64                  `protobuf:"varint,2,opt,name=totalTorrents,proto3" json:"totalTorrents,omitempty"`
	TotalResources int64                  `protobuf:"varint,3,opt,name=totalResources,proto3" json:"totalResources,omitempty"`
	TotalTraffic   int64                  `protobuf:"varint,4,opt,name=totalTraffic,proto3" json:"totalTraffic,omitempty"`
	TotalSeeders   int64                  `protobuf:"varint,5,opt,name=totalSeeders,proto3" json:"totalSeeders,omitempty"`
	TotalLeechers  int64                  `protobuf:"varint,6,opt,name=totalLeechers,proto3" json:"totalLeechers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSiteStatsResponse) Reset() {
	*x = GetSiteStatsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteStatsResponse) ProtoMessage() {}

func (x *GetSiteStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSiteStatsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{10}
}

func (x *GetSiteStatsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetSiteStatsResponse) GetTotalTorrents() int64 {
	if x != nil {
		return x.TotalTorrents
	}
	return 0
}

func (x *GetSiteStatsResponse) GetTotalResources() int64 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *GetSiteStatsResponse) GetTotalTraffic() int64 {
	if x != nil {
		return x.TotalTraffic
	}
	return 0
}

func (x *GetSiteStatsResponse) GetTotalSeeders() int64 {
	if x != nil {
		return x.TotalSeeders
	}
	return 0
}

func (x *GetSiteStatsResponse) GetTotalLeechers() int64 {
	if x != nil {
		return x.TotalLeechers
	}
	return 0
}

var File_system_v1_system_proto protoreflect.FileDescriptor

const file_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/system.proto\x12\tsystem.v1\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\aSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\"\x14\n" +
	"\x12GetSettingsRequest\"E\n" +
	"\x13GetSettingsResponse\x12.\n" +
	"\bsettings\x18\x01 \x03(\v2\x12.system.v1.SettingR\bsettings\"%\n" +
	"\x11GetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"B\n" +
	"\x12GetSettingResponse\x12,\n" +
	"\asetting\x18\x01 \x01(\v2\x12.system.v1.SettingR\asetting\"D\n" +
	"\x12SetSettingsRequest\x12.\n" +
	"\bsettings\x18\x01 \x03(\v2\x12.system.v1.SettingR\bsettings\"\x15\n" +
	"\x13SetSettingsResponse\"(\n" +
	"\x14DeleteSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x17\n" +
	"\x15DeleteSettingResponse\"\x15\n" +
	"\x13GetSiteStatsRequest\"\xf2\x01\n" +
	"\x14GetSiteStatsResponse\x12\x1e\n" +
	"\n" +
	"totalUsers\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12$\n" +
	"\rtotalTorrents\x18\x02 \x01(\x03R\rtotalTorrents\x12&\n" +
	"\x0etotalResources\x18\x03 \x01(\x03R\x0etotalResources\x12\"\n" +
	"\ftotalTraffic\x18\x04 \x01(\x03R\ftotalTraffic\x12\"\n" +
	"\ftotalSeeders\x18\x05 \x01(\x03R\ftotalSeeders\x12$\n" +
	"\rtotalLeechers\x18\x06 \x01(\x03R\rtotalLeechers2\xe2\x04\n" +
	"\rSystemService\x12u\n" +
	"\vGetSettings\x12\x1d.system.v1.GetSettingsRequest\x1a\x1e.system.v1.GetSettingsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/gapi/system/v1/settings/get\x12q\n" +
	"\n" +
	"GetSetting\x12\x1c.system.v1.GetSettingRequest\x1a\x1d.system.v1.GetSettingResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/gapi/system/v1/setting/get\x12u\n" +
	"\vSetSettings\x12\x1d.system.v1.SetSettingsRequest\x1a\x1e.system.v1.SetSettingsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/gapi/system/v1/settings/set\x12}\n" +
	"\rDeleteSetting\x12\x1f.system.v1.DeleteSettingRequest\x1a .system.v1.DeleteSettingResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/gapi/system/v1/setting/delete\x12q\n" +
	"\fGetSiteStats\x12\x1e.system.v1.GetSiteStatsRequest\x1a\x1f.system.v1.GetSiteStatsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/gapi/system/v1/statsB?Z=github.com/GoldenSheep402/Hermes/pkg/proto/system/v1;systemV1b\x06proto3"

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_system_v1_system_proto_goTypes = []any{
	(*Setting)(nil),               // 0: system.v1.Setting
	(*GetSettingsRequest)(nil),    // 1: system.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),   // 2: system.v1.GetSettingsResponse
	(*GetSettingRequest)(nil),     // 3: system.v1.GetSettingRequest
	(*GetSettingResponse)(nil),    // 4: system.v1.GetSettingResponse
	(*SetSettingsRequest)(nil),    // 5: system.v1.SetSettingsRequest
	(*SetSettingsResponse)(nil),   // 6: system.v1.SetSettingsResponse
	(*DeleteSettingRequest)(nil),  // 7: system.v1.DeleteSettingRequest
	(*DeleteSettingResponse)(nil), // 8: system.v1.DeleteSettingResponse
	(*GetSiteStatsRequest)(nil),   // 9: system.v1.GetSiteStatsRequest
	(*GetSiteStatsResponse)(nil),  // 10: system.v1.GetSiteStatsResponse
}
var file_system_v1_system_proto_depIdxs = []int32{
	0,  // 0: system.v1.GetSettingsResponse.settings:type_name -> system.v1.Setting
	0,  // 1: system.v1.GetSettingResponse.setting:type_name -> system.v1.Setting
	0,  // 2: system.v1.SetSettingsRequest.settings:type_name -> system.v1.Setting
	1,  // 3: system.v1.SystemService.GetSettings:input_type -> system.v1.GetSettingsRequest
	3,  // 4: system.v1.SystemService.GetSetting:input_type -> system.v1.GetSettingRequest
	5,  // 5: system.v1.SystemService.SetSettings:input_type -> system.v1.SetSettingsRequest
	7,  // 6: system.v1.SystemService.DeleteSetting:input_type -> system.v1.DeleteSettingRequest
	9,  // 7: system.v1.SystemService.GetSiteStats:input_type -> system.v1.GetSiteStatsRequest
	2,  // 8: system.v1.SystemService.GetSettings:output_type -> system.v1.GetSettingsResponse
	4,  // 9: system.v1.SystemService.GetSetting:output_type -> system.v1.GetSettingResponse
	6,  // 10: system.v1.SystemService.SetSettings:output_type -> system.v1.SetSettingsResponse
	8,  // 11: system.v1.SystemService.DeleteSetting:output_type -> system.v1.DeleteSettingResponse
	10, // 12: system.v1.SystemService.GetSiteStats:output_type -> system.v1.GetSiteStatsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
