// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: bonus/v1/bonus.proto

package bonusV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BonusService_GetBonusBalance_FullMethodName = "/bonus.v1.BonusService/GetBonusBalance"
	BonusService_ListBonusLogs_FullMethodName   = "/bonus.v1.BonusService/ListBonusLogs"
	BonusService_ExchangeBonus_FullMethodName   = "/bonus.v1.BonusService/ExchangeBonus"
)

// BonusServiceClient is the client API for BonusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BonusServiceClient interface {
	GetBonusBalance(ctx context.Context, in *GetBonusBalanceRequest, opts ...grpc.CallOption) (*GetBonusBalanceResponse, error)
	ListBonusLogs(ctx context.Context, in *ListBonusLogsRequest, opts ...grpc.CallOption) (*ListBonusLogsResponse, error)
	ExchangeBonus(ctx context.Context, in *ExchangeBonusRequest, opts ...grpc.CallOption) (*ExchangeBonusResponse, error)
}

type bonusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBonusServiceClient(cc grpc.ClientConnInterface) BonusServiceClient {
	return &bonusServiceClient{cc}
}

func (c *bonusServiceClient) GetBonusBalance(ctx context.Context, in *GetBonusBalanceRequest, opts ...grpc.CallOption) (*GetBonusBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBonusBalanceResponse)
	err := c.cc.Invoke(ctx, BonusService_GetBonusBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) ListBonusLogs(ctx context.Context, in *ListBonusLogsRequest, opts ...grpc.CallOption) (*ListBonusLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBonusLogsResponse)
	err := c.cc.Invoke(ctx, BonusService_ListBonusLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusServiceClient) ExchangeBonus(ctx context.Context, in *ExchangeBonusRequest, opts ...grpc.CallOption) (*ExchangeBonusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeBonusResponse)
	err := c.cc.Invoke(ctx, BonusService_ExchangeBonus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BonusServiceServer is the server API for BonusService service.
// All implementations must embed UnimplementedBonusServiceServer
// for forward compatibility.
type BonusServiceServer interface {
	GetBonusBalance(context.Context, *GetBonusBalanceRequest) (*GetBonusBalanceResponse, error)
	ListBonusLogs(context.Context, *ListBonusLogsRequest) (*ListBonusLogsResponse, error)
	ExchangeBonus(context.Context, *ExchangeBonusRequest) (*ExchangeBonusResponse, error)
	mustEmbedUnimplementedBonusServiceServer()
}

// UnimplementedBonusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBonusServiceServer struct{}

func (UnimplementedBonusServiceServer) GetBonusBalance(context.Context, *GetBonusBalanceRequest) (*GetBonusBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBonusBalance not implemented")
}
func (UnimplementedBonusServiceServer) ListBonusLogs(context.Context, *ListBonusLogsRequest) (*ListBonusLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBonusLogs not implemented")
}
func (UnimplementedBonusServiceServer) ExchangeBonus(context.Context, *ExchangeBonusRequest) (*ExchangeBonusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeBonus not implemented")
}
func (UnimplementedBonusServiceServer) mustEmbedUnimplementedBonusServiceServer() {}
func (UnimplementedBonusServiceServer) testEmbeddedByValue()                      {}

// UnsafeBonusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BonusServiceServer will
// result in compilation errors.
type UnsafeBonusServiceServer interface {
	mustEmbedUnimplementedBonusServiceServer()
}

func RegisterBonusServiceServer(s grpc.ServiceRegistrar, srv BonusServiceServer) {
	// If the following call panics, it indicates UnimplementedBonusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BonusService_ServiceDesc, srv)
}

func _BonusService_GetBonusBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBonusBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetBonusBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BonusService_GetBonusBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetBonusBalance(ctx, req.(*GetBonusBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_ListBonusLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBonusLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).ListBonusLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BonusService_ListBonusLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).ListBonusLogs(ctx, req.(*ListBonusLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BonusService_ExchangeBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).ExchangeBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BonusService_ExchangeBonus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).ExchangeBonus(ctx, req.(*ExchangeBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BonusService_ServiceDesc is the grpc.ServiceDesc for BonusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BonusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bonus.v1.BonusService",
	HandlerType: (*BonusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBonusBalance",
			Handler:    _BonusService_GetBonusBalance_Handler,
		},
		{
			MethodName: "ListBonusLogs",
			Handler:    _BonusService_ListBonusLogs_Handler,
		},
		{
			MethodName: "ExchangeBonus",
			Handler:    _BonusService_ExchangeBonus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus/v1/bonus.proto",
}
