// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user.proto

package userV1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,6,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	GroupId       string                 `protobuf:"bytes,7,opt,name=groupId,proto3" json:"groupId,omitempty"`
	BonusPoints   int64                  `protobuf:"varint,8,opt,name=bonusPoints,proto3" json:"bonusPoints,omitempty"`
	Uploaded      int64                  `protobuf:"varint,9,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	Downloaded    int64                  `protobuf:"varint,10,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	SeedTime      int64                  `protobuf:"varint,11,opt,name=seedTime,proto3" json:"seedTime,omitempty"`
	InviteCount   int32                  `protobuf:"varint,12,opt,name=inviteCount,proto3" json:"inviteCount,omitempty"`
	Passkey       string                 `protobuf:"bytes,13,opt,name=passkey,proto3" json:"passkey,omitempty"`
	LastLogin     string                 `protobuf:"bytes,14,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *User) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *User) GetBonusPoints() int64 {
	if x != nil {
		return x.BonusPoints
	}
	return 0
}

func (x *User) GetUploaded() int64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *User) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *User) GetSeedTime() int64 {
	if x != nil {
		return x.SeedTime
	}
	return 0
}

func (x *User) GetInviteCount() int32 {
	if x != nil {
		return x.InviteCount
	}
	return 0
}

func (x *User) GetPasskey() string {
	if x != nil {
		return x.Passkey
	}
	return ""
}

func (x *User) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Level           int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	MinUpload       int64                  `protobuf:"varint,5,opt,name=minUpload,proto3" json:"minUpload,omitempty"`
	MinRatio        float64                `protobuf:"fixed64,6,opt,name=minRatio,proto3" json:"minRatio,omitempty"`
	MinSeedTime     int64                  `protobuf:"varint,7,opt,name=minSeedTime,proto3" json:"minSeedTime,omitempty"`
	MaxDownloads    int32                  `protobuf:"varint,8,opt,name=maxDownloads,proto3" json:"maxDownloads,omitempty"`
	CanUpload       bool                   `protobuf:"varint,9,opt,name=canUpload,proto3" json:"canUpload,omitempty"`
	CanInvite       bool                   `protobuf:"varint,10,opt,name=canInvite,proto3" json:"canInvite,omitempty"`
	IsImmuneToRatio bool                   `protobuf:"varint,11,opt,name=isImmuneToRatio,proto3" json:"isImmuneToRatio,omitempty"`
	Color           string                 `protobuf:"bytes,12,opt,name=color,proto3" json:"color,omitempty"`
	Icon            string                 `protobuf:"bytes,13,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserGroup) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserGroup) GetMinUpload() int64 {
	if x != nil {
		return x.MinUpload
	}
	return 0
}

func (x *UserGroup) GetMinRatio() float64 {
	if x != nil {
		return x.MinRatio
	}
	return 0
}

func (x *UserGroup) GetMinSeedTime() int64 {
	if x != nil {
		return x.MinSeedTime
	}
	return 0
}

func (x *UserGroup) GetMaxDownloads() int32 {
	if x != nil {
		return x.MaxDownloads
	}
	return 0
}

func (x *UserGroup) GetCanUpload() bool {
	if x != nil {
		return x.CanUpload
	}
	return false
}

func (x *UserGroup) GetCanInvite() bool {
	if x != nil {
		return x.CanInvite
	}
	return false
}

func (x *UserGroup) GetIsImmuneToRatio() bool {
	if x != nil {
		return x.IsImmuneToRatio
	}
	return false
}

func (x *UserGroup) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UserGroup) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RealUpload     int64                  `protobuf:"varint,2,opt,name=realUpload,proto3" json:"realUpload,omitempty"`
	RealDownload   int64                  `protobuf:"varint,3,opt,name=realDownload,proto3" json:"realDownload,omitempty"`
	Ratio          float64                `protobuf:"fixed64,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	PublishedCount int32                  `protobuf:"varint,5,opt,name=publishedCount,proto3" json:"publishedCount,omitempty"`
	SeedingCount   int32                  `protobuf:"varint,6,opt,name=seedingCount,proto3" json:"seedingCount,omitempty"`
	DownloadCount  int32                  `protobuf:"varint,7,opt,name=downloadCount,proto3" json:"downloadCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserProfileResponse) GetRealUpload() int64 {
	if x != nil {
		return x.RealUpload
	}
	return 0
}

func (x *GetUserProfileResponse) GetRealDownload() int64 {
	if x != nil {
		return x.RealDownload
	}
	return 0
}

func (x *GetUserProfileResponse) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *GetUserProfileResponse) GetPublishedCount() int32 {
	if x != nil {
		return x.PublishedCount
	}
	return 0
}

func (x *GetUserProfileResponse) GetSeedingCount() int32 {
	if x != nil {
		return x.SeedingCount
	}
	return 0
}

func (x *GetUserProfileResponse) GetDownloadCount() int32 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

type ResetPasskeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasskeyRequest) Reset() {
	*x = ResetPasskeyRequest{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasskeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasskeyRequest) ProtoMessage() {}

func (x *ResetPasskeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasskeyRequest.ProtoReflect.Descriptor instead.
func (*ResetPasskeyRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

type ResetPasskeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passkey       string                 `protobuf:"bytes,1,opt,name=passkey,proto3" json:"passkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasskeyResponse) Reset() {
	*x = ResetPasskeyResponse{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasskeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasskeyResponse) ProtoMessage() {}

func (x *ResetPasskeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasskeyResponse.ProtoReflect.Descriptor instead.
func (*ResetPasskeyResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ResetPasskeyResponse) GetPasskey() string {
	if x != nil {
		return x.Passkey
	}
	return ""
}

type GetUserPasskeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasskeyRequest) Reset() {
	*x = GetUserPasskeyRequest{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasskeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasskeyRequest) ProtoMessage() {}

func (x *GetUserPasskeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasskeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserPasskeyRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

type GetUserPasskeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passkey       string                 `protobuf:"bytes,1,opt,name=passkey,proto3" json:"passkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasskeyResponse) Reset() {
	*x = GetUserPasskeyResponse{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasskeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasskeyResponse) ProtoMessage() {}

func (x *GetUserPasskeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasskeyResponse.ProtoReflect.Descriptor instead.
func (*GetUserPasskeyResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserPasskeyResponse) GetPasskey() string {
	if x != nil {
		return x.Passkey
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateUserGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *UserGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserGroupRequest) Reset() {
	*x = CreateUserGroupRequest{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupRequest) ProtoMessage() {}

func (x *CreateUserGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateUserGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUserGroupRequest) GetGroup() *UserGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateUserGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserGroupResponse) Reset() {
	*x = CreateUserGroupResponse{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupResponse) ProtoMessage() {}

func (x *CreateUserGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateUserGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

type GetUserGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupRequest) Reset() {
	*x = GetUserGroupRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupRequest) ProtoMessage() {}

func (x *GetUserGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupRequest.ProtoReflect.Descriptor instead.
func (*GetUserGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *UserGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupResponse) Reset() {
	*x = GetUserGroupResponse{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupResponse) ProtoMessage() {}

func (x *GetUserGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupResponse.ProtoReflect.Descriptor instead.
func (*GetUserGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserGroupResponse) GetGroup() *UserGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type ListUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsRequest) Reset() {
	*x = ListUserGroupsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsRequest) ProtoMessage() {}

func (x *ListUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

type ListUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*UserGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsResponse) Reset() {
	*x = ListUserGroupsResponse{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsResponse) ProtoMessage() {}

func (x *ListUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *ListUserGroupsResponse) GetGroups() []*UserGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type UpdateUserGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *UserGroup             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserGroupRequest) Reset() {
	*x = UpdateUserGroupRequest{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupRequest) ProtoMessage() {}

func (x *UpdateUserGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUserGroupRequest) GetGroup() *UserGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateUserGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserGroupResponse) Reset() {
	*x = UpdateUserGroupResponse{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupResponse) ProtoMessage() {}

func (x *UpdateUserGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

type DeleteUserGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupRequest) Reset() {
	*x = DeleteUserGroupRequest{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupRequest) ProtoMessage() {}

func (x *DeleteUserGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteUserGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupResponse) Reset() {
	*x = DeleteUserGroupResponse{}
	mi := &file_user_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupResponse) ProtoMessage() {}

func (x *DeleteUserGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{25}
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\"\xa4\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\aisAdmin\x18\x05 \x01(\bR\aisAdmin\x12\x1c\n" +
	"\tisEnabled\x18\x06 \x01(\bR\tisEnabled\x12\x18\n" +
	"\agroupId\x18\a \x01(\tR\agroupId\x12 \n" +
	"\vbonusPoints\x18\b \x01(\x03R\vbonusPoints\x12\x1a\n" +
	"\buploaded\x18\t \x01(\x03R\buploaded\x12\x1e\n" +
	"\n" +
	"downloaded\x18\n" +
	" \x01(\x03R\n" +
	"downloaded\x12\x1a\n" +
	"\bseedTime\x18\v \x01(\x03R\bseedTime\x12 \n" +
	"\vinviteCount\x18\f \x01(\x05R\vinviteCount\x12\x18\n" +
	"\apasskey\x18\r \x01(\tR\apasskey\x12\x1c\n" +
	"\tlastLogin\x18\x0e \x01(\tR\tlastLogin\x12\x1c\n" +
	"\tcreatedAt\x18\x0f \x01(\tR\tcreatedAt\"\xf7\x02\n" +
	"\tUserGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1c\n" +
	"\tminUpload\x18\x05 \x01(\x03R\tminUpload\x12\x1a\n" +
	"\bminRatio\x18\x06 \x01(\x01R\bminRatio\x12 \n" +
	"\vminSeedTime\x18\a \x01(\x03R\vminSeedTime\x12\"\n" +
	"\fmaxDownloads\x18\b \x01(\x05R\fmaxDownloads\x12\x1c\n" +
	"\tcanUpload\x18\t \x01(\bR\tcanUpload\x12\x1c\n" +
	"\tcanInvite\x18\n" +
	" \x01(\bR\tcanInvite\x12(\n" +
	"\x0fisImmuneToRatio\x18\v \x01(\bR\x0fisImmuneToRatio\x12\x14\n" +
	"\x05color\x18\f \x01(\tR\x05color\x12\x12\n" +
	"\x04icon\x18\r \x01(\tR\x04icon\"\x10\n" +
	"\x0eGetUserRequest\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"'\n" +
	"\x15GetUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x87\x02\n" +
	"\x16GetUserProfileResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x1e\n" +
	"\n" +
	"realUpload\x18\x02 \x01(\x03R\n" +
	"realUpload\x12\"\n" +
	"\frealDownload\x18\x03 \x01(\x03R\frealDownload\x12\x14\n" +
	"\x05ratio\x18\x04 \x01(\x01R\x05ratio\x12&\n" +
	"\x0epublishedCount\x18\x05 \x01(\x05R\x0epublishedCount\x12\"\n" +
	"\fseedingCount\x18\x06 \x01(\x05R\fseedingCount\x12$\n" +
	"\rdownloadCount\x18\a \x01(\x05R\rdownloadCount\"G\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"[\n" +
	"\x15UpdatePasswordRequest\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16UpdatePasswordResponse\"\x15\n" +
	"\x13ResetPasskeyRequest\"0\n" +
	"\x14ResetPasskeyResponse\x12\x18\n" +
	"\apasskey\x18\x01 \x01(\tR\apasskey\"\x17\n" +
	"\x15GetUserPasskeyRequest\"2\n" +
	"\x16GetUserPasskeyResponse\x12\x18\n" +
	"\apasskey\x18\x01 \x01(\tR\apasskey\"B\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"N\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x16CreateUserGroupRequest\x12(\n" +
	"\x05group\x18\x01 \x01(\v2\x12.user.v1.UserGroupR\x05group\"\x19\n" +
	"\x17CreateUserGroupResponse\"%\n" +
	"\x13GetUserGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x14GetUserGroupResponse\x12(\n" +
	"\x05group\x18\x01 \x01(\v2\x12.user.v1.UserGroupR\x05group\"\x17\n" +
	"\x15ListUserGroupsRequest\"D\n" +
	"\x16ListUserGroupsResponse\x12*\n" +
	"\x06groups\x18\x01 \x03(\v2\x12.user.v1.UserGroupR\x06groups\"B\n" +
	"\x16UpdateUserGroupRequest\x12(\n" +
	"\x05group\x18\x01 \x01(\v2\x12.user.v1.UserGroupR\x05group\"\x19\n" +
	"\x17UpdateUserGroupResponse\"(\n" +
	"\x16DeleteUserGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteUserGroupResponse2\xea\n" +
	"\n" +
	"\vUserService\x12[\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/gapi/user/v1/info\x12s\n" +
	"\x0eGetUserProfile\x12\x1e.user.v1.GetUserProfileRequest\x1a\x1f.user.v1.GetUserProfileResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/gapi/user/v1/profile\x12f\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/gapi/user/v1/update\x12t\n" +
	"\x0eUpdatePassword\x12\x1e.user.v1.UpdatePasswordRequest\x1a\x1f.user.v1.UpdatePasswordResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/gapi/user/v1/password\x12s\n" +
	"\fResetPasskey\x12\x1c.user.v1.ResetPasskeyRequest\x1a\x1d.user.v1.ResetPasskeyResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/gapi/user/v1/passkey/reset\x12s\n" +
	"\x0eGetUserPasskey\x12\x1e.user.v1.GetUserPasskeyRequest\x1a\x1f.user.v1.GetUserPasskeyResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/gapi/user/v1/passkey\x12a\n" +
	"\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/gapi/user/v1/list\x12{\n" +
	"\x0fCreateUserGroup\x12\x1f.user.v1.CreateUserGroupRequest\x1a .user.v1.CreateUserGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/gapi/user/v1/group/create\x12o\n" +
	"\fGetUserGroup\x12\x1c.user.v1.GetUserGroupRequest\x1a\x1d.user.v1.GetUserGroupResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/gapi/user/v1/group/get\x12v\n" +
	"\x0eListUserGroups\x12\x1e.user.v1.ListUserGroupsRequest\x1a\x1f.user.v1.ListUserGroupsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/gapi/user/v1/group/list\x12{\n" +
	"\x0fUpdateUserGroup\x12\x1f.user.v1.UpdateUserGroupRequest\x1a .user.v1.UpdateUserGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/gapi/user/v1/group/update\x12{\n" +
	"\x0fDeleteUserGroup\x12\x1f.user.v1.DeleteUserGroupRequest\x1a .user.v1.DeleteUserGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/gapi/user/v1/group/deleteB;Z9github.com/GoldenSheep402/Hermes/pkg/proto/user/v1;userV1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_user_v1_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: user.v1.User
	(*UserGroup)(nil),               // 1: user.v1.UserGroup
	(*GetUserRequest)(nil),          // 2: user.v1.GetUserRequest
	(*GetUserResponse)(nil),         // 3: user.v1.GetUserResponse
	(*GetUserProfileRequest)(nil),   // 4: user.v1.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),  // 5: user.v1.GetUserProfileResponse
	(*UpdateUserRequest)(nil),       // 6: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),      // 7: user.v1.UpdateUserResponse
	(*UpdatePasswordRequest)(nil),   // 8: user.v1.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),  // 9: user.v1.UpdatePasswordResponse
	(*ResetPasskeyRequest)(nil),     // 10: user.v1.ResetPasskeyRequest
	(*ResetPasskeyResponse)(nil),    // 11: user.v1.ResetPasskeyResponse
	(*GetUserPasskeyRequest)(nil),   // 12: user.v1.GetUserPasskeyRequest
	(*GetUserPasskeyResponse)(nil),  // 13: user.v1.GetUserPasskeyResponse
	(*ListUsersRequest)(nil),        // 14: user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),       // 15: user.v1.ListUsersResponse
	(*CreateUserGroupRequest)(nil),  // 16: user.v1.CreateUserGroupRequest
	(*CreateUserGroupResponse)(nil), // 17: user.v1.CreateUserGroupResponse
	(*GetUserGroupRequest)(nil),     // 18: user.v1.GetUserGroupRequest
	(*GetUserGroupResponse)(nil),    // 19: user.v1.GetUserGroupResponse
	(*ListUserGroupsRequest)(nil),   // 20: user.v1.ListUserGroupsRequest
	(*ListUserGroupsResponse)(nil),  // 21: user.v1.ListUserGroupsResponse
	(*UpdateUserGroupRequest)(nil),  // 22: user.v1.UpdateUserGroupRequest
	(*UpdateUserGroupResponse)(nil), // 23: user.v1.UpdateUserGroupResponse
	(*DeleteUserGroupRequest)(nil),  // 24: user.v1.DeleteUserGroupRequest
	(*DeleteUserGroupResponse)(nil), // 25: user.v1.DeleteUserGroupResponse
}
var file_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.GetUserResponse.user:type_name -> user.v1.User
	0,  // 1: user.v1.GetUserProfileResponse.user:type_name -> user.v1.User
	0,  // 2: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	0,  // 3: user.v1.ListUsersResponse.users:type_name -> user.v1.User
	1,  // 4: user.v1.CreateUserGroupRequest.group:type_name -> user.v1.UserGroup
	1,  // 5: user.v1.GetUserGroupResponse.group:type_name -> user.v1.UserGroup
	1,  // 6: user.v1.ListUserGroupsResponse.groups:type_name -> user.v1.UserGroup
	1,  // 7: user.v1.UpdateUserGroupRequest.group:type_name -> user.v1.UserGroup
	2,  // 8: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	4,  // 9: user.v1.UserService.GetUserProfile:input_type -> user.v1.GetUserProfileRequest
	6,  // 10: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	8,  // 11: user.v1.UserService.UpdatePassword:input_type -> user.v1.UpdatePasswordRequest
	10, // 12: user.v1.UserService.ResetPasskey:input_type -> user.v1.ResetPasskeyRequest
	12, // 13: user.v1.UserService.GetUserPasskey:input_type -> user.v1.GetUserPasskeyRequest
	14, // 14: user.v1.UserService.ListUsers:input_type -> user.v1.ListUsersRequest
	16, // 15: user.v1.UserService.CreateUserGroup:input_type -> user.v1.CreateUserGroupRequest
	18, // 16: user.v1.UserService.GetUserGroup:input_type -> user.v1.GetUserGroupRequest
	20, // 17: user.v1.UserService.ListUserGroups:input_type -> user.v1.ListUserGroupsRequest
	22, // 18: user.v1.UserService.UpdateUserGroup:input_type -> user.v1.UpdateUserGroupRequest
	24, // 19: user.v1.UserService.DeleteUserGroup:input_type -> user.v1.DeleteUserGroupRequest
	3,  // 20: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	5,  // 21: user.v1.UserService.GetUserProfile:output_type -> user.v1.GetUserProfileResponse
	7,  // 22: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	9,  // 23: user.v1.UserService.UpdatePassword:output_type -> user.v1.UpdatePasswordResponse
	11, // 24: user.v1.UserService.ResetPasskey:output_type -> user.v1.ResetPasskeyResponse
	13, // 25: user.v1.UserService.GetUserPasskey:output_type -> user.v1.GetUserPasskeyResponse
	15, // 26: user.v1.UserService.ListUsers:output_type -> user.v1.ListUsersResponse
	17, // 27: user.v1.UserService.CreateUserGroup:output_type -> user.v1.CreateUserGroupResponse
	19, // 28: user.v1.UserService.GetUserGroup:output_type -> user.v1.GetUserGroupResponse
	21, // 29: user.v1.UserService.ListUserGroups:output_type -> user.v1.ListUserGroupsResponse
	23, // 30: user.v1.UserService.UpdateUserGroup:output_type -> user.v1.UpdateUserGroupResponse
	25, // 31: user.v1.UserService.DeleteUserGroup:output_type -> user.v1.DeleteUserGroupResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
