// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tracker/v1/tracker.proto

package trackerV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackerService_GetTorrentPeers_FullMethodName = "/tracker.v1.TrackerService/GetTorrentPeers"
	TrackerService_ListSnatches_FullMethodName    = "/tracker.v1.TrackerService/ListSnatches"
	TrackerService_GetUserSnatches_FullMethodName = "/tracker.v1.TrackerService/GetUserSnatches"
)

// TrackerServiceClient is the client API for TrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackerServiceClient interface {
	GetTorrentPeers(ctx context.Context, in *GetTorrentPeersRequest, opts ...grpc.CallOption) (*GetTorrentPeersResponse, error)
	ListSnatches(ctx context.Context, in *ListSnatchesRequest, opts ...grpc.CallOption) (*ListSnatchesResponse, error)
	GetUserSnatches(ctx context.Context, in *GetUserSnatchesRequest, opts ...grpc.CallOption) (*GetUserSnatchesResponse, error)
}

type trackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackerServiceClient(cc grpc.ClientConnInterface) TrackerServiceClient {
	return &trackerServiceClient{cc}
}

func (c *trackerServiceClient) GetTorrentPeers(ctx context.Context, in *GetTorrentPeersRequest, opts ...grpc.CallOption) (*GetTorrentPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTorrentPeersResponse)
	err := c.cc.Invoke(ctx, TrackerService_GetTorrentPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) ListSnatches(ctx context.Context, in *ListSnatchesRequest, opts ...grpc.CallOption) (*ListSnatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnatchesResponse)
	err := c.cc.Invoke(ctx, TrackerService_ListSnatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerServiceClient) GetUserSnatches(ctx context.Context, in *GetUserSnatchesRequest, opts ...grpc.CallOption) (*GetUserSnatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSnatchesResponse)
	err := c.cc.Invoke(ctx, TrackerService_GetUserSnatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackerServiceServer is the server API for TrackerService service.
// All implementations must embed UnimplementedTrackerServiceServer
// for forward compatibility.
type TrackerServiceServer interface {
	GetTorrentPeers(context.Context, *GetTorrentPeersRequest) (*GetTorrentPeersResponse, error)
	ListSnatches(context.Context, *ListSnatchesRequest) (*ListSnatchesResponse, error)
	GetUserSnatches(context.Context, *GetUserSnatchesRequest) (*GetUserSnatchesResponse, error)
	mustEmbedUnimplementedTrackerServiceServer()
}

// UnimplementedTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackerServiceServer struct{}

func (UnimplementedTrackerServiceServer) GetTorrentPeers(context.Context, *GetTorrentPeersRequest) (*GetTorrentPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTorrentPeers not implemented")
}
func (UnimplementedTrackerServiceServer) ListSnatches(context.Context, *ListSnatchesRequest) (*ListSnatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnatches not implemented")
}
func (UnimplementedTrackerServiceServer) GetUserSnatches(context.Context, *GetUserSnatchesRequest) (*GetUserSnatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSnatches not implemented")
}
func (UnimplementedTrackerServiceServer) mustEmbedUnimplementedTrackerServiceServer() {}
func (UnimplementedTrackerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackerServiceServer will
// result in compilation errors.
type UnsafeTrackerServiceServer interface {
	mustEmbedUnimplementedTrackerServiceServer()
}

func RegisterTrackerServiceServer(s grpc.ServiceRegistrar, srv TrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackerService_ServiceDesc, srv)
}

func _TrackerService_GetTorrentPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).GetTorrentPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_GetTorrentPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).GetTorrentPeers(ctx, req.(*GetTorrentPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_ListSnatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).ListSnatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_ListSnatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).ListSnatches(ctx, req.(*ListSnatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackerService_GetUserSnatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSnatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServiceServer).GetUserSnatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackerService_GetUserSnatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServiceServer).GetUserSnatches(ctx, req.(*GetUserSnatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackerService_ServiceDesc is the grpc.ServiceDesc for TrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracker.v1.TrackerService",
	HandlerType: (*TrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTorrentPeers",
			Handler:    _TrackerService_GetTorrentPeers_Handler,
		},
		{
			MethodName: "ListSnatches",
			Handler:    _TrackerService_ListSnatches_Handler,
		},
		{
			MethodName: "GetUserSnatches",
			Handler:    _TrackerService_GetUserSnatches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracker/v1/tracker.proto",
}
